'use client';

import { ThemeProvider } from '@/lib/theme-context';
import '../styles/globals.css';
import { Inter } from 'next/font/google';

// const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayoutClient({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider>
      <html lang="en">
        {/* <body className={inter.className}> */}
        <body>
          <main className="h-screen w-full">{children}</main>
        </body>
      </html>
    </ThemeProvider>
  );
}
