import '../styles/globals.css';

import RootLayoutClient from './layout.client';

export const metadata = {
  icons: {
    // icon: 'favicon.png',
  },
  title: 'BearNote',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <RootLayoutClient>{children}</RootLayoutClient>;
}
