import { getUser } from '@/server/rsc/user.rsc';
import Toolbar from './toolbar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getUser();
  if (!user) return;
  return (
    <div id="dashboard" className="flex h-screen justify-center">
      <div
        id="content-wrapper"
        className="relative flex w-[640px] max-w-full bg-warm-100"
      >
        {children}
        <div
          id="toolbar"
          className="absolute bottom-0 flex w-full border border-b-0 p-4 font-light dark:border-grey-700 dark:bg-grey-800 [&>*]:flex [&>*]:w-1/4 [&>*]:justify-center"
        >
          <div>
            <span>Note</span>
          </div>
          <div>
            <span>Writing</span>
          </div>
          <div>
            <span>Reading</span>
          </div>
          <div>
            <span>Resource</span>
          </div>
        </div>
      </div>
    </div>
  );
}
