import { getUser } from '@/server/rsc/user.rsc';
import Footer from './layout-footer.client';

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
};

export default async function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getUser();
  if (!user) return;

  return (
    <div id="dashboard" className="h-screen w-full">
      <main className="flex max-h-screen justify-center overflow-y-clip">
        {children}
      </main>
      <Footer />
    </div>
  );
}
